import Header from '../components/Header/Header';
import '../styles/globals.css';

export const metadata = {
  title: 'DoodlePlay',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
